"""
Scene Beat Orchestrator.

Operationalizes the locked story premise ("Investigation is a Mirror") and character web
into concrete gameplay scenes. Ensures every investigation choice reflects the player's
psychological wound.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum
from src.character_identity import WoundType
from src.narrative.story_structure import get_story_structure
from src.narrative.character_web import get_character_web, CharacterCorner

class ScenePurpose(str, Enum):
    """Why this scene exists in the narrative."""
    MIRROR_INVESTIGATION = "mirror_investigation"  # Investigation choice mirrors wound
    CHARACTER_OPPOSITION = "character_opposition"  # Uses character web tension
    PREMISE_TEST = "premise_test"  # Tests understanding of "Mirror" principle

@dataclass
class SceneChoice:
    """A choice in a generated scene."""
    id: str
    text: str
    mirrors_wound: str  # How this choice reflects the player's archetype
    consequence: str
    is_growth_choice: bool = False
    relationship_change: float = 0.0
    archetype_signal: Optional[WoundType] = None

@dataclass
class GeneratedScene:
    """A complete scene generated by the orchestrator."""
    scene_id: str
    scene_type: ScenePurpose
    premise_alignment: str  # Always "The Investigation is a Mirror"
    setup: str
    choices: List[SceneChoice]
    character_web_integration: Dict[str, Any]
    archetype_focus: WoundType
    story_progress: float

# ============================================================================
# MIRROR INVESTIGATION TEMPLATES
# ============================================================================

INVESTIGATION_MIRRORS = {
    WoundType.CONTROLLER: {
        "locked_room": {
            "setup": "You've found the captain's quarters sealed. The door is locked. Multiple approaches present themselves.",
            "choices": [
                SceneChoice(
                    id="force_door",
                    text="Force the door open. You need access NOW.",
                    mirrors_wound="CONTROLLER - need for immediate control through force",
                    consequence="Door opens but you damage evidence. Torres questions your methods.",
                    relationship_change=-0.1
                ),
                SceneChoice(
                    id="find_key",
                    text="Find who has the key. Control through information.",
                    mirrors_wound="CONTROLLER - need to control all variables",
                    consequence="You interrogate crew about keys. Efficient but controlling.",
                    relationship_change=0.0
                ),
                SceneChoice(
                    id="wait_observe",
                    text="Wait and observe. Someone will open it eventually.",
                    mirrors_wound="GROWTH - letting go of need for immediate control",
                    consequence="Ember opens it naturally later. She trusts you more for not forcing.",
                    is_growth_choice=True,
                    relationship_change=0.2
                )
            ]
        },
        "encrypted_files": {
            "setup": "The captain's personal files are encrypted. You could hack them, ask for help, or wait.",
            "choices": [
                SceneChoice(
                    id="hack_now",
                    text="Hack the encryption yourself. You need to know.",
                    mirrors_wound="CONTROLLER - must control information flow",
                    consequence="Success, but Torres sees you. 'Can't trust anyone, can you?'",
                    relationship_change=-0.2
                ),
                SceneChoice(
                    id="delegate_kai",
                    text="Ask Kai to decrypt them. He's better at this.",
                    mirrors_wound="CONTROLLER - delegating but still controlling outcome",
                    consequence="Kai helps. You're learning to trust expertise.",
                    relationship_change=0.1
                ),
                SceneChoice(
                    id="leave_encrypted",
                    text="Leave them. If they're meant to be read, they will be.",
                    mirrors_wound="GROWTH - surrendering need to control all knowledge",
                    consequence="Dr. Okonkwo decrypts them later, shares key findings voluntarily.",
                    is_growth_choice=True,
                    relationship_change=0.3
                )
            ]
        }
    },
    WoundType.JUDGE: {
        "suspect_interview": {
            "setup": "Yuki has agreed to answer questions. How you approach this reveals everything.",
            "choices": [
                SceneChoice(
                    id="prosecute",
                    text="I know you're guilty. Just confess.",
                    mirrors_wound="JUDGE - pre-judging without full evidence",
                    consequence="Yuki shuts down. 'You've already decided. Why bother asking?'",
                    relationship_change=-0.4
                ),
                SceneChoice(
                    id="neutral_questions",
                    text="Walk me through your movements that night.",
                    mirrors_wound="JUDGE - seeking evidence to support judgment",
                    consequence="Professional but cold. You get facts, not truth.",
                    relationship_change=0.0
                ),
                SceneChoice(
                    id="human_first",
                    text="How are you holding up? This must be difficult.",
                    mirrors_wound="GROWTH - seeing the human before the suspect",
                    consequence="Yuki is surprised. Opens up slightly. Real connection possible.",
                    is_growth_choice=True,
                    relationship_change=0.3
                )
            ]
        }
    },
    WoundType.GHOST: {
        "emotional_scene": {
            "setup": "Ember is crying in the corridor. She saw something that reminded her of the captain.",
            "choices": [
                SceneChoice(
                    id="avoid",
                    text="[Walk past quietly. Don't get involved.]",
                    mirrors_wound="GHOST - emotional avoidance, fear of connection",
                    consequence="Ember notices. 'Everyone leaves.' Trust damaged.",
                    relationship_change=-0.3
                ),
                SceneChoice(
                    id="practical",
                    text="Do you need anything? Water? A med kit?",
                    mirrors_wound="GHOST - offering practical help to avoid emotional presence",
                    consequence="Helpful but distant. Ember accepts but feels alone.",
                    relationship_change=0.0
                ),
                SceneChoice(
                    id="present",
                    text="[Sit down beside her. Say nothing. Just be there.]",
                    mirrors_wound="GROWTH - choosing presence over distance",
                    consequence="Ember leans against you. 'Thank you for staying.' Deep bond.",
                    is_growth_choice=True,
                    relationship_change=0.4
                )
            ]
        }
    },
    WoundType.SAVIOR: {
        "crew_conflict": {
            "setup": "Torres and Kai are arguing about the fuel shortage. You could intervene or let them resolve it.",
            "choices": [
                SceneChoice(
                    id="save_both",
                    text="Stop fighting. I'll handle this myself.",
                    mirrors_wound="SAVIOR - need to save everyone, taking all responsibility",
                    consequence="You 'fix' it but they resent being managed. No growth for anyone.",
                    relationship_change=-0.2
                ),
                SceneChoice(
                    id="mediate",
                    text="Let's all calm down and find a solution together.",
                    mirrors_wound="SAVIOR - still controlling but collaborative",
                    consequence="Productive but you're still the center. Moderate outcome.",
                    relationship_change=0.1
                ),
                SceneChoice(
                    id="step_back",
                    text="[Say nothing. Let them work it out.]",
                    mirrors_wound="GROWTH - trusting others to save themselves",
                    consequence="They fight, then resolve it. Stronger for having done it themselves.",
                    is_growth_choice=True,
                    relationship_change=0.3
                )
            ]
        }
    }
}

# ============================================================================
# SCENE ORCHESTRATOR
# ============================================================================

class SceneBeatOrchestrator:
    """Generates scenes that operationalize the story premise and character web."""
    
    def __init__(self):
        self.story_structure = get_story_structure()
        self.character_web = get_character_web()
    
    def generate_investigation_scene(
        self,
        player_archetype: WoundType,
        story_progress: float,
        context: str = "general"
    ) -> GeneratedScene:
        """
        Generate an investigation scene that mirrors the player's wound.
        
        Every choice reflects their archetype, with one growth option.
        """
        
        # Get archetype-specific investigation templates
        archetype_templates = INVESTIGATION_MIRRORS.get(player_archetype, {})
        
        if not archetype_templates:
            # Fallback to CONTROLLER if archetype not implemented
            archetype_templates = INVESTIGATION_MIRRORS[WoundType.CONTROLLER]
        
        # Select template based on context or random
        template_key = list(archetype_templates.keys())[0]  # Simple selection for now
        template = archetype_templates[template_key]
        
        # Find relevant character from web for integration
        web_character = self._get_opposing_character(player_archetype)
        
        return GeneratedScene(
            scene_id=f"mirror_investigation_{player_archetype.value}_{template_key}",
            scene_type=ScenePurpose.MIRROR_INVESTIGATION,
            premise_alignment="The Investigation is a Mirror",
            setup=template["setup"],
            choices=template["choices"],
            character_web_integration={
                "npc_involved": web_character["id"] if web_character else None,
                "corner_tension": self._get_corner_tension(player_archetype),
                "opposition_type": "diagonal" if web_character else None
            },
            archetype_focus=player_archetype,
            story_progress=story_progress
        )
    
    def _get_opposing_character(self, player_archetype: WoundType) -> Optional[Dict]:
        """Get a character from the web who opposes the player's archetype."""
        # Map archetypes to character web corners
        archetype_to_corner = {
            WoundType.CONTROLLER: CharacterCorner.TRUST,  # Controller needs to learn trust
            WoundType.JUDGE: CharacterCorner.VULNERABILITY,  # Judge needs to see complexity
            WoundType.GHOST: CharacterCorner.VULNERABILITY,  # Ghost needs connection
            WoundType.SAVIOR: CharacterCorner.DISTANCE,  # Savior needs boundaries
        }
        
        target_corner = archetype_to_corner.get(player_archetype)
        if not target_corner:
            return None
        
        # Find character in that corner
        for char in self.character_web["characters"]:
            if char["corner"] == target_corner.value:
                return char
        
        return None
    
    def _get_corner_tension(self, player_archetype: WoundType) -> str:
        """Describe the thematic tension for this archetype."""
        tensions = {
            WoundType.CONTROLLER: "Control vs. Trust",
            WoundType.JUDGE: "Judgment vs. Complexity",
            WoundType.GHOST: "Distance vs. Connection",
            WoundType.SAVIOR: "Saving vs. Boundaries",
            WoundType.CYNIC: "Cynicism vs. Hope"
        }
        return tensions.get(player_archetype, "Unknown tension")
    
    def validate_premise_alignment(self, scene: GeneratedScene) -> float:
        """
        Validate that a scene serves the "Mirror" principle.
        Returns score 0.0-1.0.
        """
        score = 0.0
        
        # Check 1: Does every choice reflect the archetype?
        if all(choice.mirrors_wound for choice in scene.choices):
            score += 0.4
        
        # Check 2: Is there a growth choice?
        if any(choice.is_growth_choice for choice in scene.choices):
            score += 0.3
        
        # Check 3: Is character web integrated?
        if scene.character_web_integration.get("npc_involved"):
            score += 0.3
        
        return score

def get_scene_orchestrator() -> SceneBeatOrchestrator:
    """Factory function for the orchestrator."""
    return SceneBeatOrchestrator()
